name: Test & Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        pip install poetry==1.2.0

    - name: Install dependencies
      run: |
        poetry install

    - name: Export requirements
      run: |
        poetry export -f requirements.txt --output requirements.txt --without-hashes

    - name: Run tests
      run: |
        pytest
